apiVersion: flows.knative.dev/v1alpha1
kind: Flow
metadata:
  name: iot-example
  namespace: default
spec:
  serviceAccountName: binder
  trigger:
    service: gcppubsub
    eventType: receive
    resource: gcppubsub/receive
    parameters:
      projectID: jgrayston-serverless
      topic: device-telemetry
  action:
    target:
      kind: Route
      apiVersion: serving.knative.dev/v1alpha1
      name: iot-function

